### ISSUE TITLE
One or more extentions failed to load

### ISSUE THREAD

**Issue by twophyro** [zachsaw/MPDN_Extensions#200]
Whenever i install MPDN Extensions it gives me this message "One or more extensions failed to load! The extentions you have installed may be incompatable with the current version MPDN. You are strongly advisde to correct this problem before using MPDN."

Setup:
MPDN Latest Nov 12 2015 (Version 2.45.5.3574)
Extensions v1.24.2

**Comment by zachsaw** [comment]
Did you install via installer?

**Comment by twophyro** [comment]
Yes, i used the installer for both the player and the extensions.

**Comment by twophyro** [comment]
MediaPlayerDotNet_x64_2_44_0_3451_Installer
MPDN-Extensions_v1.22.0_Installer

These are working together and they are the latest respective versions.

**Comment by twophyro** [comment]
I've been waiting now for awhile but none of the newer versions are working together.

The latest stable versions are still:
MediaPlayerDotNet_x64_2_44_0_3451_Installer
MPDN-Extensions_v1.22.0_Installer

I have .net 3.5(2.0) and 4.6.

I would love to replace MPC HC with MadVR with MPDN.

**Comment by twophyro** [comment]
"Exception has been thrown by the target of an invocation"

**Comment by twophyro** [comment]
It appears that only the x64 versions is having problems.

**Comment by zachsaw** [comment]
That's really strange as I can't replicate it. Does this happen on all your systems or just the one?

**Comment by twophyro** [comment]
i've only tried it on one system but the x86 version works.
I will try it on a different system.

**Comment by twophyro** [comment]
Application: MediaPlayerDotNet.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
   at System.RuntimeTypeHandle.CreateInstance(System.RuntimeType, Boolean, Boolean, Boolean ByRef, System.RuntimeMethodHandleInternal ByRef, Boolean ByRef)
   at System.RuntimeType.CreateInstanceSlow(Boolean, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Activator.CreateInstance(System.Type, Boolean)
   at System.Activator.CreateInstance(System.Type)
   at Microsoft.ClearScript.Util.MiscHelpers.TryCreateCOMObject[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, System.String, System.__Canon ByRef)
   at Microsoft.ClearScript.Windows.ProcessDebugManagerWrapper64.TryCreate(Microsoft.ClearScript.Windows.ProcessDebugManagerWrapper ByRef)
   at Microsoft.ClearScript.Windows.WindowsScriptEngine+<>c__DisplayClass2.<.ctor>b__0()
   at Microsoft.ClearScript.ScriptEngine.ScriptInvoke[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`1<System.__Canon>)
   at Microsoft.ClearScript.Windows.WindowsScriptEngine..ctor(System.String, System.String, Microsoft.ClearScript.Windows.WindowsScriptEngineFlags)
   at Microsoft.ClearScript.Windows.JScriptEngine..ctor(System.String, System.String, Microsoft.ClearScript.Windows.WindowsScriptEngineFlags)
   at Mpdn.Extensions.Framework.Scripting.ScriptEngine`3[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor()
   at Mpdn.Extensions.Framework.Scripting.RenderScriptEngine.get_Instance()
   at Mpdn.Extensions.RenderScripts.Mpdn.ScriptedRenderChain.ScriptedRenderChain..ctor()

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeTypeHandle.CreateInstance(System.RuntimeType, Boolean, Boolean, Boolean ByRef, System.RuntimeMethodHandleInternal ByRef, Boolean ByRef)
   at System.RuntimeType.CreateInstanceSlow(Boolean, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Activator.CreateInstance[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]()
   at Mpdn.Extensions.Framework.Config.MemConfig`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor()
   at Mpdn.Extensions.Framework.Config.ExtensionUi`3[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Settings()
   at Mpdn.Extensions.Framework.Chain.ChainUi`4[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Dispose(Boolean)
   at Mpdn.Extensions.Framework.Chain.ChainUi`4[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Finalize()

**Comment by twophyro** [comment]
Faulting application name: MediaPlayerDotNet.exe, version: 2.46.0.3600, time stamp: 0x56cfee69
Faulting module name: KERNELBASE.dll, version: 10.0.10586.162, time stamp: 0x56cd45b4
Exception code: 0xe0434352
Fault offset: 0x0000000000071f28
Faulting process id: 0x27c0
Faulting application start time: 0x01d197283fdf6903
Faulting application path: C:\Users\Daniel\Desktop\MediaPlayerDotNet_x64_2_46_0_3600\MediaPlayerDotNet.exe
Faulting module path: C:\WINDOWS\system32\KERNELBASE.dll
Report Id: 350e77c1-e1d2-44eb-a2d5-a06f0976bceb
Faulting package full name: 
Faulting package-relative application ID:

**Comment by twophyro** [comment]
Zachsaw, i've tested the latest apr 14 build on a virtual system and it worked so it must be something wrong with my system, might reinstall windows.

**Comment by twophyro** [comment]
This problem is no longer active as of v2.48.0/v1.30.0.
The problem was only active for the 64-bit build.
